apiVersion: v1
kind: Namespace
metadata:
  name: free-service
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: free-service-quota
  namespace: free-service
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
